include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "build/**"
    - ".dart_tool/**"
    - ".idea/**"
    - ".vscode/**"
  errors:
    use_build_context_synchronously: ignore
    empty_catches: ignore
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    non_constant_identifier_names: ignore
    library_prefixes: ignore
    void_checks: ignore
    unrelated_type_equality_checks: ignore
    use_setters_to_change_properties: ignore
    missing_required_param: error
    missing_return: error
    unnecessary_getters_setters: error
    annotate_overrides: error
    avoid_init_to_null: error
    await_only_futures: error
    empty_statements: error
    
  
  plugins:
    - custom_lint

language:
  strict-casts: false
  strict-inference: false
  strict-raw-types: false


linter:
  rules:
    - always_declare_return_types
    - annotate_overrides
    - avoid_empty_else
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_unnecessary_containers
    - avoid_void_async
    - cancel_subscriptions
    - close_sinks
    - constant_identifier_names
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - depend_on_referenced_packages
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - no_duplicate_case_values
    - non_constant_identifier_names
    - only_throw_errors
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_contains
    - prefer_final_fields
    - prefer_final_locals
    - prefer_foreach
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_single_quotes
    - prefer_spread_collections
    - recursive_getters
    - slash_for_doc_comments
    - sort_child_properties_last
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - valid_regexps